### ISSUE TITLE
Javascript Digital Clock 

### ISSUE THREAD

**Issue by DanCQ** [DanCQ/Digital-Clock--Javascript#1]
<a href="https://github.com/DanCQ/Digital-Clock--Javascript">The Javascript Digital Clock: Github Repository</a>
A digital clock dynamically running in real time.
It displays the current date and time, for the viewer's location.

Feel free to make suggestions, or your own version.
[The Javascript Digital Clock Website](https://digital-clock--javascript.pages.dev/)

I'm trying to see how collaboration with others can happen on Github.
Tell me if I need to enable a feature, if you cannot contribute freely.

I've labeled this issue as "good first issue" for beginner friendly.

**Comment by FirminoMassango** [comment]
Hello Mr. DanCQ, I'm interested in contributing to open source project, sou I'll try to help you...

**Comment by DanCQ** [comment]
> 

Nice to see you here Firmino. Have fun.

**Comment by abitsalihu** [comment]
Hey @DanCQ I would like to implement a new UI Design for this, I can work on it and then send the UI "screenshot". If you like it you can implement it, if not it's fine :)

**Comment by DanCQ** [comment]
Sure give it a try.

**Comment by abitsalihu** [comment]
I'll send a pull request tomorrow, as it's a bit late right now.  :)

**Comment by DanCQ** [comment]
Okay.

**Comment by DanCQ** [comment]
You made it look like an art piece Abit. Pretty.

**Comment by abitsalihu** [comment]
Thanks man, really appericiate it 🙂

**Comment by DanCQ** [comment]
I think I will close this issue as the project as become too complex to be user friendly, but I will open another issue asking for further 'enhancement'.
